### ISSUE TITLE
Unable to access edit.php

### ISSUE THREAD

**Issue by italonascimento** [alterfw/alter#20] opened 2016-10-19 14:34 UTC
When I enable the theme I've just created using Alter, I can't access wordpress edit.php anymore. I'm unable to edit custom posts as well as pages and native posts.

I'm using wordpress 4.6.1. May that be a compatibility issue?

**Comment by sergiopvilar** [comment] 2016-10-19 14:38
@italonascimento please give me more details. Did you got an error or something?

**Comment by italonascimento** [comment] 2016-10-19 14:46
When I click on menu button to edit posts, pages or any cpt, I just get home page instead.

URL redirects correctly to edit.php, but home page is rendered (as it's a fresh new project, home page is Alter's default "hello world").

Even if I try with an untouched installation, with no Models, I'm unable to edit posts or pages.

**Comment by italonascimento** [comment] 2016-11-01 19:54
Any news on this?

**Comment by paulitolinhares** [comment] 2017-05-30 00:15
I'm having the same problem, the URL gets changed to `/wp-admin/edit.php?post_type=release` but the view that gets rendered is the one I've set for `/` route

**Comment by sergiopvilar** [comment] 2017-06-02 22:14
Sorry for the huge delay, unfortunately I'm no longer actively maintaining this project as I would like to do.

This issue has been caused by some inconsistences in HpttFoundation component and  should be fixed by [Ampersand's 0.2.16 release](https://github.com/alterfw/ampersand/releases/tag/v0.2.16), you just need to run `composer update` no receive the update.

**Closed as completed by sergiopvilar** 2017-06-02 22:14 UTC
Labels: bug
